import Hero from '@/components/Hero';
import Slider from '@/components/Slider';
import Head from 'next/head'
import { SliderData } from '@/components/SliderData';
import Instagram from '@/components/Instagram';

export default function Home() {
  return (
    <>
      <Head>
        <title>Photography Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
      </Head>
     <Hero heading='Capture Photography' message='I capture moments in nature and keep them alive.' />
     <Slider slides={SliderData} />
     <Instagram />
    
    </>
  );
}
